name: smart_fitness_tracker
description: A new Flutter project.

# App version
version: 1.0.0+1

# Dart SDK constraint (important â€“ ye hi error fix karega)
environment:
  sdk: '^3.10.0'

# Project dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Real sensor step counter & fitness data
  pedometer: ^4.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# Flutter section (default)
flutter:
  uses-material-design: true


